### ISSUE TITLE
Generic reused

### ISSUE THREAD

**Issue by uittorio** [uittorio/ts-auto-mock#1]
Example
```ts
interface Interface<T> {
  generic: T;
}

const mock1 = createMock<Interface<string>>();
mock.generic // "" CORRECT
const mock2 = createMock<Interface<number>>();
mock2.generic // "" WRONG. IT should be 0
```

**Comment by Pmyl** [comment]
This happens due to our reusing of mock factories that are related to the type. Once the factory is created for `Interface<string>` then all the following usages of `Interface<*>` will have the generic `string`.

My opinion is that we need to enhance the factory parameterizing it to receive the generics keys and shift a small part of the calculations at runtime.
